version: '3.1'

services:
 postgres_db:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: flask_db
  volumes:
    - ./data/postgres:/var/lib/postgresql/data
  ports:
    - 5432:5432

 mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: flask_db
    volumes:
      - ./docker/mongo_db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
