version: '3.1'

services:
 db:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: flask_db
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
  ports:
    - 5432:5432